### ISSUE TITLE
repo-health-check

### ISSUE THREAD

**Issue by byjrack** [todogroup/awesome-ospo#36]
[repo-health-check](https://github.com/dogweather/repo-health-check)

So I don't use this whole cloth, but found the methodology valuable on how to distill a number of metrics into a single range score.  100% agree measure choice and weighting is a bit subjective, but the intent is solid and can provide a simple G/Y/R sort of indicator.

**Comment by willnorris** [comment]
Looks like this got added in 062fa17b7f0.
